apiVersion: apps/v1
kind: Deployment
metadata:
  name: power-app
  namespace: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: power-app
  template:
    metadata:
      labels:
        app: power-app
    spec:
      containers:
        - name: power-app
          image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 200m
              memory: 256Mi
          ports:
          - containerPort: 80
            protocol: TCP
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 10.40.1.61
          - 172.24.4.12
          - 10.96.0.10
        searches:
          - svc.cluster.local
          - cluster.local
        options:
          - name: ndots
            value: "5"

---

apiVersion: v1
kind: Service
metadata:
  name: power-app
  namespace: jenkins
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: power-app
